---
# tasks file for cdh-opti

- name: debug os family
  debug: msg="{{ ansible_os_family }} {{ansible_distribution}} {{ansible_distribution_release }}" 
  tags:
    - cdh

- name: Include OS-specific variables.
  include_vars: '{{ ansible_distribution }}.yml'
  tags:
   - optimize
  
- name: Include optimized network settings
  include_vars: 'network.yml'
  tags:
   - optimize
  
- name: Include limits
  include_vars: 'limits.yml'
  tags:
   - optimize

- name: Include ntpd Configuration
  include: ntp.yml
  
- name: Include Huge Pages Configuration
  include: huge-pages.yml

- name: Include VM Swappiness
  include: vm-swappiness.yml

- name: Include Network Optimizations
  include: network.yml

#- name: Include File Formatting/Mounting Configuration
#  include: mounts.yml

- name: Include Limits Configuration
  include: limits.yml

- name: Include SElinux Configuration
  include: selinux.yml

- name: Include IPtables Configuration
  include: iptables.yml